### ISSUE TITLE
Conversions UPC to GTIN-14

### ISSUE THREAD

**Issue by JCapriotti** [nager/Nager.ArticleNumber#1]
Hello,
I was thinking about extending your library to do conversions from UPC to GTIN-14. Would this be something you'd want to pull into your repo?

Thanks,
Jason

**Comment by tinohager** [comment]
Hi,
Yes i think all conversions stuff of article numbers is right here.

**Comment by JCapriotti** [comment]
I submitted PR #2... hoping it works for you and can also be added to the NuGet package.

**Comment by tinohager** [comment]
Hi i publish a new nuget package this week, thanks

**Comment by tinohager** [comment]
the new package is published, thanks for the update

**Comment by JCapriotti** [comment]
Great, thank you.
