### ISSUE TITLE
ArticleNumberType.Isbn13 won't be recognized

### ISSUE THREAD

**Issue by PanantukanFMA** [nager/Nager.ArticleNumber#3]
I tried this:
`Nager.ArticleNumber.ArticleNumberType articleNumberType = Nager.ArticleNumber.ArticleNumberHelper.GetArticleNumberType("9783551775849");`

articleNumberType was recognized as ArticleNumberType.Ean13 but it is actually a ArticleNumberType.Isbn13 (Prefix 978)

But
`if (Nager.ArticleNumber.ArticleNumberHelper.IsValidIsbn13("9783551775849"))`
and
`if (Nager.ArticleNumber.ArticleNumberHelper.IsValidEan("9783551775849"))`
both are true...

2 Issues:

1. ArticleNumberHelper.GetArticleNumberType does not recognize ArticleNumberType.Isbn13 but ArticleNumberHelper.IsValidIsbn13 does
2. ArticleNumberHelper.IsValidEan does recognize ArticleNumberType.Isbn13 as EAN

**Comment by tinohager** [comment]
i think it is not possible do identify the type 100%...

https://www.barcoding.com/blog/bookland-13-ean-13-and-isbn-numbers-one-in-the-same/
