### ISSUE TITLE
String incorrectly identified as ean13

### ISSUE THREAD

**Issue by Magnus12** [nager/Nager.ArticleNumber#6]
`ArticleNumberHelper.GetArticleNumberType("849172008847 ")` is reported as type EAN13 but I think it should be unknown or maybe UPC (if the traling space is ignored)

**Comment by tinohager** [comment]
https://www.gs1.org/services/check-digit-calculator

![image](https://user-images.githubusercontent.com/8215186/135483055-ad7ff68c-fe9f-4814-a612-7eed6a54725a.png)

**Comment by tinohager** [comment]
@Magnus12 please check the new nuget package

**Comment by Magnus12** [comment]
Wow, you are quick. 👍
